// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLPnixaJ60GQGOmuT6PNjbr8Iqv_ma8Mw',
    appId: '1:270547476938:android:36c3e619eaa0aa05f3ef33',
    messagingSenderId: '270547476938',
    projectId: 'eventbuddy-86f9b',
    storageBucket: 'eventbuddy-86f9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCquUKJ8lFG8SHKw2F6Tzw15BmMcTylYHs',
    appId: '1:270547476938:ios:837550ac3a3caee1f3ef33',
    messagingSenderId: '270547476938',
    projectId: 'eventbuddy-86f9b',
    storageBucket: 'eventbuddy-86f9b.firebasestorage.app',
    iosBundleId: 'com.example.eventBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCquUKJ8lFG8SHKw2F6Tzw15BmMcTylYHs',
    appId: '1:270547476938:ios:837550ac3a3caee1f3ef33',
    messagingSenderId: '270547476938',
    projectId: 'eventbuddy-86f9b',
    storageBucket: 'eventbuddy-86f9b.firebasestorage.app',
    iosBundleId: 'com.example.eventBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMKYvxs4TehhHfoD25DlFQ-WA3Vbf1Mrk',
    appId: '1:270547476938:web:635ffa43a5688b85f3ef33',
    messagingSenderId: '270547476938',
    projectId: 'eventbuddy-86f9b',
    authDomain: 'eventbuddy-86f9b.firebaseapp.com',
    storageBucket: 'eventbuddy-86f9b.firebasestorage.app',
  );
}
